### ISSUE TITLE
Upload Artifacts Failing in CI

### ISSUE THREAD

**Issue by Czarified** [Czarified/hyperstruct#113]
[Link to pipeline ](https://github.com/Czarified/hyperstruct/actions/runs/12868930377/job/35876615281)

Upload artifacts GitHub Action cannot find any files that match my search pattern. There's a couple things going on here:

1. Coverage.py only seems to create the coverage files when executed on Windows. I can see the file created locally when I run nox on my dev machine, and the Windows Tests job has the file created. On Linux and MacOS, the ls command is issued after the nox run (within the same job step) and doesn't show any coverage file created.
2. Even on the Windows Test job, when we use the GitHub Action `upload-artifact` in the   next step, it can't find any files that match the pattern.

The specific segment of the code is in `.github/workflows/tests.yml`:
```yaml
    - name: Run Nox
      run: |
        nox --python=${{ matrix.python }}
        ls

    - name: Upload coverage data
      if: always() && matrix.session == 'tests'
      uses: "actions/upload-artifact@v4"
      with:
        name: coverage-data-${{matrix.python}}-${{matrix.os}}
        path: hyperstruct/*/.coverage*
```

Patterns I've tried: `.coverage*, ./coverage*, hyperstruct/.coverage*, hyperstruct/*/.coverage*`

I'm completely stumped on this one, and it's annoying the hell out of me, so I'm gonna leave it here. Unfortunately, I think this CI failure prevents any new versions from getting through CD and released to PyPI.

All my work has been conducted in the fuselage branch. CI/CD in main is outdated.
